# Generated by Django 3.1.3 on 2020-11-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('medicine', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('don_thuoc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don_thuoc', to='medicine.donthuoc')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('chuoi_kham', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don_dich_vu', to='clinic.chuoikham')),
            ],
        ),
    ]
