# Generated by Django 3.1.4 on 2020-12-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20201207_2056'),
        ('finance', '0002_hoadonlamsang_hoadontong'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadontong',
            name='lich_hen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don_lich_hen', to='clinic.lichhenkham'),
        ),
    ]
