# Generated by Django 3.1.4 on 2020-12-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_hoadontong_lich_hen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoadonlamsang',
            old_name='tong_tien',
            new_name='gia_tien',
        ),
    ]
