# Generated by Django 3.1.3 on 2020-11-29 11:57

import clinic.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='(84|0[3|5|7|8|9])+([0-9]{8})\\b')])),
                ('ho_ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('cmnd_cccd', models.CharField(max_length=13, null=True, unique=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('1', 'Nam'), ('0', 'Nu')], max_length=1, null=True)),
                ('anh_dai_dien', models.FileField(blank=True, max_length=1000, null=True, upload_to=clinic.models.file_url)),
                ('dia_chi', models.TextField(blank=True, max_length=1000, null=True)),
                ('chuc_nang', models.CharField(choices=[('1', 'Nguoi Dung'), ('2', 'Le Tan'), ('3', 'Bac Si Lam Sang'), ('4', 'Bac Si Chuyen Khoa'), ('5', 'Nhan vien Phong Tai Chinh'), ('6', 'Nhan vien Phong Thuoc')], default='1', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tai_kham', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_dam_nhan', models.ForeignKey(blank=True, null=True, on_delete=models.SET(clinic.models.get_sentinel_user), related_name='bac_si_chuoi_kham', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), related_name='chuoi_kham', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DichVuKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dvkt', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_dvkt', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_gia', models.CharField(blank=True, max_length=50, null=True)),
                ('don_gia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quyet_dinh', models.CharField(blank=True, max_length=10, null=True)),
                ('cong_bo', models.CharField(blank=True, max_length=10, null=True)),
                ('ma_cosokcb', models.CharField(blank=True, max_length=20, null=True)),
                ('ten_dich_vu', models.CharField(blank=True, max_length=255, null=True)),
                ('bac_si_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_si_dam_nhan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileKetQua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=clinic.models.file_url)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LichHenKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(auto_now=True, null=True)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), related_name='benh_nhan_hen_kham', to=settings.AUTH_USER_MODEL)),
                ('nguoi_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=models.SET(clinic.models.get_sentinel_user), related_name='nguoi_phu_trach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhongChucNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_chuc_nang', models.CharField(max_length=255)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('dich_vu_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phong_chuc_nang_theo_dich_vu', to='clinic.dichvukham')),
            ],
        ),
        migrations.CreateModel(
            name='TinhTrangPhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kha_dung', models.BooleanField(default=True)),
                ('thoi_gian_dong_cua', models.DateTimeField(null=True)),
                ('thoi_gian_mo_cua', models.DateTimeField(null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longtitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_chuoi_kham', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_khoa_kham', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiLichHen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_trang_thai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhongChucNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_cho', models.PositiveIntegerField(blank=True, null=True)),
                ('thoi_gian_trung_binh', models.PositiveIntegerField(blank=True, help_text='Đơn vị(phút)', null=True)),
                ('status', models.BooleanField(default=True)),
                ('phong_chuc_nang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_phong_chuc_nang', to='clinic.phongchucnang')),
            ],
        ),
        migrations.CreateModel(
            name='PhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_kham', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.URLField()),
                ('tinh_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.tinhtrangphongkham')),
            ],
        ),
        migrations.CreateModel(
            name='PhanKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_hiem', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_lam_sang', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), related_name='bac_si', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_khoa_kham', to='clinic.chuoikham')),
                ('dich_vu_kham', models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_dich_vu), related_name='dich_vu_kham', to='clinic.dichvukham')),
                ('trang_thai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.trangthaikhoakham')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiLichHen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('lich_hen_kham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='clinic.lichhenkham')),
                ('trang_thai_lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai_lich_hen', to='clinic.trangthailichhen')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
                ('trang_thai_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthaikhoakham')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.chuoikham')),
                ('trang_thai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthaichuoikham')),
            ],
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='trang_thai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthailichhen'),
        ),
        migrations.CreateModel(
            name='KetQuaTongQuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ket_qua', models.CharField(blank=True, max_length=50, null=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('ket_luan', models.TextField(blank=True, null=True)),
                ('chuoi_kham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ket_qua_tong_quat', to='clinic.chuoikham')),
            ],
        ),
        migrations.CreateModel(
            name='KetQuaChuyenKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ket_qua', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('ket_luan', models.TextField(blank=True, null=True)),
                ('ket_qua_tong_quat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_chuyen_khoa', to='clinic.ketquatongquat')),
            ],
        ),
        migrations.CreateModel(
            name='GiaDichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_dich_vu_kham', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gia_dich_vu_kham', to='clinic.dichvukham')),
            ],
        ),
        migrations.CreateModel(
            name='FileKetQuaTongQuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tong_quat', to='clinic.fileketqua')),
                ('ket_qua_tong_quat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ket_qua_tong_quat', to='clinic.ketquatongquat')),
            ],
        ),
        migrations.CreateModel(
            name='FileKetQuaChuyenKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chuyen_khoa', to='clinic.fileketqua')),
                ('ket_qua_chuyen_khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ket_qua_chuyen_khoa', to='clinic.ketquachuyenkhoa')),
            ],
        ),
        migrations.AddField(
            model_name='chuoikham',
            name='trang_thai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai', to='clinic.trangthaichuoikham'),
        ),
        migrations.CreateModel(
            name='BaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bao_hiem', models.CharField(max_length=255)),
                ('dang_bao_hiem', models.SmallIntegerField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField()),
                ('thoi_gian_chinh_sua', models.DateTimeField()),
                ('id_dich_vu_kham', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bao_hiem_dich_vu_kham', to='clinic.dichvukham')),
            ],
        ),
    ]
