# Generated by Django 3.1.4 on 2020-12-05 08:29

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_dichvukham_bao_hiem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to=clinic.models.file_url)),
                ('tom_tat', models.TextField(blank=True, null=True)),
                ('noi_dung', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
