# Generated by Django 3.1.4 on 2020-12-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_baidang'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuoikham',
            name='lich_hen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.lichhenkham'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nu')], max_length=10, null=True),
        ),
    ]
