# Generated by Django 3.1.4 on 2020-12-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20201207_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvukham',
            name='phong_chuc_nang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.phongchucnang'),
        ),
    ]
