# Generated by Django 3.1.4 on 2020-12-12 07:34

import clinic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_dichvukham_phong_chuc_nang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phongchucnang',
            name='dich_vu_kham',
        ),
        migrations.AlterField(
            model_name='dichvukham',
            name='phong_chuc_nang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dich_vu_kham_theo_phong', to='clinic.phongchucnang'),
        ),
        migrations.AlterField(
            model_name='phankhoakham',
            name='dich_vu_kham',
            field=models.ForeignKey(on_delete=models.SET(clinic.models.get_sentinel_dich_vu), related_name='phan_khoa_dich_vu', to='clinic.dichvukham'),
        ),
    ]
