# Generated by Django 3.1.4 on 2020-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20201212_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvukham',
            name='stt',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
