# Generated by Django 3.1.3 on 2020-11-29 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicine.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongTy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_cong_ty', models.CharField(max_length=255, verbose_name='Tên Công Ty')),
                ('giay_phep_kinh_doanh', models.CharField(max_length=255, verbose_name='Giấy phép kinh doanh')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('so_lien_lac', models.CharField(max_length=255, verbose_name='Số liên lạc')),
                ('email', models.CharField(max_length=255, verbose_name='Email công ty')),
                ('mo_ta', models.CharField(max_length=255, verbose_name='Mô tả công ty')),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Công Ty',
                'verbose_name_plural': 'Công Ty',
            },
        ),
        migrations.CreateModel(
            name='DonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_thuoc', models.CharField(max_length=50, unique=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('bac_si_ke_don', models.ForeignKey(on_delete=models.SET(medicine.models.get_sentinel_user), related_name='bac_si_ke_don', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(on_delete=models.SET(medicine.models.get_sentinel_user), related_name='don_thuoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn Thuốc',
                'verbose_name_plural': 'Đơn Thuốc',
            },
        ),
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ten_thuoc', models.CharField(max_length=255)),
                ('ma_thuoc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mã thuốc')),
                ('loai_thuoc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thuốc')),
                ('gia_mua', models.CharField(max_length=50, null=True, verbose_name='Giá nhập')),
                ('gia_ban', models.CharField(max_length=50, null=True, verbose_name='Giá bán')),
                ('so_lo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số Lô')),
                ('so_ke_tai_quay', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số Kệ')),
                ('han_su_dung', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('ngay_san_xuat', models.DateField(blank=True, null=True, verbose_name='Ngày sản xuất')),
                ('mo_ta', models.CharField(max_length=255, verbose_name='Mô tả')),
                ('tac_dung_phu', models.CharField(max_length=255, verbose_name='Tác dụng phụ')),
                ('quy_cach', models.IntegerField(verbose_name='Quy cách đóng gói')),
                ('so_luong_kha_dung', models.IntegerField(verbose_name='Số lượng khả dụng')),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
                ('id_cong_ty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuoc_cong_ty', to='medicine.congty')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Đơn Thuốc',
                'verbose_name_plural': 'Trạng Thái Đơn Thuốc',
            },
        ),
        migrations.CreateModel(
            name='ThuocLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateTimeField(verbose_name='Ngày giờ')),
                ('quy_trinh', models.CharField(choices=[('I', 'In'), ('O', 'Out')], max_length=1, verbose_name='Quy trình')),
                ('so_luong', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuoc_logs', to='medicine.thuoc', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Thuốc Log',
                'verbose_name_plural': 'Thuốc Log',
            },
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.TextField()),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('don_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.donthuoc')),
                ('trang_thai_don_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.trangthaidonthuoc')),
            ],
        ),
        migrations.CreateModel(
            name='KeDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cach_dung', models.TextField()),
                ('so_luong', models.PositiveIntegerField()),
                ('ghi_chu', models.TextField()),
                ('bao_hiem', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('don_thuoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ke_don', to='medicine.donthuoc')),
                ('thuoc', models.ForeignKey(on_delete=models.SET(medicine.models.get_sentinel_thuoc), to='medicine.thuoc')),
            ],
            options={
                'verbose_name': 'Kê Đơn Thuốc',
                'verbose_name_plural': 'Kê Đơn Thuốc',
            },
        ),
        migrations.CreateModel(
            name='GiaThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_thuoc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gia_thuoc', to='medicine.thuoc')),
            ],
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.trangthaidonthuoc'),
        ),
        migrations.CreateModel(
            name='ChiTietThuoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_muoi', models.CharField(max_length=255, verbose_name='Tên thuốc con')),
                ('ham_luong', models.CharField(max_length=255, verbose_name='Hàm lượng')),
                ('mo_ta', models.CharField(max_length=255, verbose_name='Mô tả')),
                ('ngay_gio_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ tạo')),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
                ('id_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.thuoc', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Chi Tiết Thuốc',
                'verbose_name_plural': 'Chi Tiết Thuốc',
            },
        ),
        migrations.CreateModel(
            name='BaoHiemThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muc_bao_hiem', models.PositiveIntegerField()),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_thuoc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bao_hiem_thuoc', to='medicine.thuoc')),
            ],
        ),
    ]
