# Generated by Django 3.1.3 on 2020-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20201203_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='bao_hiem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
