# Generated by Django 3.1.3 on 2020-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_thuoc_bao_hiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='cong_bo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
