# Generated by Django 3.1.4 on 2020-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_thuoc_cong_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='ma_thuoc',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
