# Generated by Django 3.1.4 on 2020-12-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_thuoc_ma_thuoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thuoc',
            old_name='id_cong_ty',
            new_name='cong_ty',
        ),
    ]
